config/routes.rb
Opinion::Application.routes.draw do
  resources :search_suggestions

  root 'welcome#index'
  resources :welcome
  resources :users
  resources :sessions
  resources :votes

  resources :changes do
    resources :comments
    member { post :vote }
  end
  resources :categories

  resources :states 

  post '/create' => 'vote#create' 

     get '/about', controller: 'welcome', action: 'about'

  

end

app/models/change.rb
class Change < ActiveRecord::Base


	belongs_to :user
  belongs_to :state
	has_many :votes, :dependent => :destroy

  has_many :categorizations, :dependent => :destroy
  has_many :categories, through: :categorizations

  has_many :comments

  accepts_nested_attributes_for :categories
  accepts_nested_attributes_for :comments
  
	mount_uploader :picture, PictureUploader

  # validates_inclusion_of :format, in: %w( jpg gif png ), message: "extension %{value} is not included in the list"
  # validates_length_of :username, minimum: 3, too_short: 'please enter at least 3 characters'

	def trending_algorithm(gravity = 1.8)
		# For a given change
    # Find all votes
    # Points is the difference of upvotes and downvotes
    # Time is the difference between now and when the change was created (in hours)
    # gravity is fixed, but can override if necessary  
    points = self.aggregate
    time = ((Time.now - self.created_at) / 5760).round
    rank = (points - 1).to_f / ((time + 2)**gravity)
	end


  def aggregate
    self.up_votes - self.down_votes
  end


  def up_votes
     votes.select{|vote| vote.value == 1 }.size
  end

  def down_votes
    votes.select{|vote| vote.value == -1 }.size
  end


  def total_votes
     self.up_votes - self.down_votes
  end

  def total_voted
     self.up_votes + self.down_votes
  end

end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController

  def new
    @change = Change.new
    @change.categorizations.build
    @categories = Category.all
  end

  def create
		@change = Change.create(change_params)
    params["change"]["category_id"].each do |num|
      n = Category.find_by_name(num)
      c = Categorization.create(change_id: @change.id, category_id: n.id)
    end
		@change.user_id = session[:user_id]
    
   respond_to do |format|
  		if @change.save!
        format.html { redirect_to change_path(@change.id), notice: 'Created An Opinion' }
      end
    end
  end


  def show
    @change = Change.joins(:categories).find(params[:id])
  end


  def vote
    @k = current_user.vote_for(params[:id], params[:value]) if current_user
    respond_to do |format|
        format.js
    end
  end


private
  def change_params
    params.require(:change).permit! #(:name, :description, :picture, :user_id, :state_id, :category_id)
  end

  def find_state
     State.where(name: params[:search].capitalize).pop.id
  end

    def vote_params
    params.require(:vote).permit!
  end


end

app/helpers/changes_helper.rb
module ChangesHelper

 def twitter_handles(senates, sep = ", @")
 	 senates.map {|senate| senate.contact.twiter }.join sep
 end
end

app/views/changes/_change.html.erb
<h3 class="text-center"><%= @change.name %></h3>


	<div class="intro-box text-center" id="<%= @change.id %>">
		<div class="change_wrapper">
			<p class="mutted"><%= @change.description %></p>
  


			<p><%= link_to "Created By: #{@change.user.username}", user_path(@change.user_id) if @change.user %>
			<p><%= image_tag @change.picture_url(:large) if @change.picture.url %></p>

			<% @change.categories.each do |cat| %>
			<div class="glyphicon glyphicon-star-empty"></div> <%=link_to cat.name.upcase, category_path(cat.id) %>
		<% end %>
		</div>
	</div>

app/views/changes/_repersenatives_holder.html.erb
<div class="space"></div>


	
		<% if !current_user %>
			<h5 class="text-center">Not from California?  <%= link_to "Create an Account", new_user_path %> and get your local representative's data</h5>
    <% end %>
    
  	
		<div class="small_space"></div>
		<% state_selector.senates.each do |senator| %>
			<div class="col-md-6 text-center change_wrapper">
				<h4><%= senator.first_name %> <%= senator.last_name %></h4>
				<p><%= senator.party.name %> Party</p>
				<p><%= link_to "@#{senator.contact.twiter}", "https://www.twitter.com/#{senator.contact.twiter}", id: "tweet" %></p>
				<p><%= link_to "Facebook", "https://www.facebook.com/#{senator.contact.facebook}" %></p>
				<p><%= senator.contact.phone %></p>
				
			</div>
		<% end %>

app/views/changes/_representatives.html.erb
	<div class="row text-center">
	
	<div class="row">
		<h3 >Tell Your <%= current_user.state.name %> Representatives</h3>

		<% current_user.state.senates.each do |senator| %>
		<div class="col-md-6">
			<p>Name: <%= senator.first_name %> <%= senator.last_name %></p>
			<p>Party: <%= senator.party %></p>
			<p><%= link_to "Twitter", "https://www.facebook.com/#{senator.twitter}" %>
			<%= link_to "Facebook", "https://www.facebook.com/#{senator.facebook}" %></p>
		</div>
		<% end %>
</div>

app/views/changes/_stats.html.erb
<h1 class="text-center">Voting Stats</h1>

<table class="table table-hover text-center">
	<tr>
  <td>Aggregate</td>
  <td>Total Up</td> 
  <td>Total Down</td>
   <td>Total Voted</td>
	</tr>
	<tr>
	  <td><%= @change.total_votes %></td>
	  <td><%= @change.up_votes %></td> 
	  <td><%= @change.down_votes %></td>
	  <td><%= @change.total_voted %></td>
	</tr>
</table>

app/views/changes/_twitter.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-via="<%= twitter_handles(state_selector.senates) %>" data-size="large">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/changes/_vote.html.erb
<div class="space"></div>
<div class="space"></div>

<div class="text-center">
	<h2>Vote</h2>

	 <h1><%=  link_to image_tag("thumb_up.png"), vote_change_path(@change, value: 1), "data-original-title" => "You must be logged in to vote",  method: "post", remote: true, class: vote_users %>
	<span id="total_votes"><%=  @change.total_votes %></span>
	<%=  link_to image_tag("thumb_down.png"), vote_change_path(@change, value: -1), "data-original-title" => "You must be logged in to vote",  method: "post", remote: true, class: vote_users  %></h1>
</div>

app/views/changes/new.html.erb
<div class="row change_wrapper">
	<div class="col-md-6 text-center">
		<!-- <div class="change_wrapper"> -->
			<%= form_for @change, :html => {:role => "form", multipart: true} do |t| %>
			<%= render "shared/error_messages", :target => @change %>
			<div class="form-group">
				<%= t.label :name %>
				<%= t.text_field :name, placeholder: "this is your title", class: "form-control", autofocus: true, required: true %>
			</div>
			<div class="form-group">
				<%= t.label :description %>
				<%= t.text_area :description, placeholder: "tell us about your opinions", class: "form-control", required: true %>
			</div>
			<div class="form-group btn btn-file">
			 <%= t.file_field :picture, required: true %>
			</div>
			<h3>Select a Category</h3>
			<% @categories.each do |cat| %>
				<%= check_box_tag("change[category_id][]", cat.name) %> <%= cat.name %>
			<% end %>
<br />
<br />


	<h3>All finished? </h3>
		<p><%= t.submit "Create Opinion", class: "btn btn-default"%></p>
		<% end %>
	</div>

		<div class="col-md-6 text-center">
			<h4><div id="name">This is Your Title</div></h4>
			<div id="description">Tell us about your opinions...</div>
      <%= image_tag("placeholder2.png", id: "blah", class: "thumb") %>
			<!-- <img id="blah" src="/placeholder.png" class="thumb" alt="your image here" /> -->
			<div id="category"></div>
	</div>
</div>

app/views/changes/show.html.erb
<%= title "#{@change.name}" %>

<div class="row">
	<div class="col-sm-7">
		<%= render "changes/change" %>
	</div>

	<div class="col-sm-5">
		<%= render "changes/vote" %>
		<h4 class="text-center" >Tell Your <%= state_selector.name %> Senators</h4>

		<div class="text-center"><%= render "changes/twitter" %></div>
		<%= render "changes/repersenatives_holder" %>
	</div>
</div>

<div class="row">
	<div class="col-sm-10 col-sm-offset-1">
		<%= render "changes/stats" %>
	</div>
</div>

<h2 class="page-header text-center">Join the Discussion</h2>
	<%= render "comments/form" %>


	<div id="added_comments" class="col-sm-8 col-sm-offset-2"></div>

<div id="comments">
	<%= render @change.comments.reverse %>
</div>

app/views/changes/vote.js.erb
var current_count = Number($("#total_votes").text() )
var new_count = ( current_count + (Number("<%= @k %>")) )
$("#total_votes").replaceWith('<span id="total_votes">' + new_count + '</span>')

app/views/changes/vote2.js.erb
$("<p>" + "<%= @total_votes %>" + "</p>").appendTo(".votes").html;