config/routes.rb
Opinion::Application.routes.draw do
  resources :search_suggestions

  root 'welcome#index'
  resources :welcome
  resources :users
  resources :sessions
  resources :votes

  resources :changes do
    resources :comments
    member { post :vote }
  end
  resources :categories

  resources :states 

  post '/create' => 'vote#create' 

     get '/about', controller: 'welcome', action: 'about'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_ancestry
	belongs_to :change
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController







  def new
    @comment = Comment.new(:parent_id => params[:parent_id])
    # @comment.parent_id = params[:parent_id]
  @change = Change.find(params[:change_id])
    @comment.change_id = params[:change_id]
  

   
  end

	def create
        @change = Change.find(params[:change_id])
        @comment = @change.comments.create(comment_params)
       
        @comment.parent_id = params["comment"]["parent_id"]
        
        @comment.save!

    respond_to do |format|
        format.html { redirect_to change_path(@change) }
        format.js 
		end
	end




  def comment_params
    params.require(:comment).permit(:parent_id, :content, :id, :change_id, :user_id, :ancestry)
  end



end

app/helpers/comments_helper.rb
module CommentsHelper

	def nested_comments(comments)
	 comments.map do |comment, sub_comments|
	    render(comment) + content_tag(:div)
	  end.join.html_safe
	end
end

app/views/comments/_comment.html.erb
<% if comment.content %>
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<div class="comment">
			
			  <%= comment.content %>
			  <div class="text-right">
				  <%# "created at: #{comment.created_at.to_date}" if comment.created_at %>

				  <%# link_to "reply", new_change_comment_path(@change, :parent_id => comment.id), remote: true, id: "new_link#{comment.id}" %>
				</div>
			
      </div>
			</div>
		</div>

<% end %>

app/views/comments/_comment_form.html.erb
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
				<%= form_for([@change, @change.comments.build], :html => {:role => "form"}, remote: true) do |t| %>
				<%= t.hidden_field :parent_id, :value => params[:parent_id] %>
				<div class="form-group">
					<%= t.text_area :content, class: "form-control", required: true %>
				</div>
					<%= t.submit class: "btn btn-default" %>
				<% end %>
		</div>
	</div>

app/views/comments/_form.html.erb
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
				<%= form_for([@change, @change.comments.build], :html => {:role => "form"}, remote: true) do |t| %>
				<%= t.hidden_field :parent_id, :value => params[:parent_id] %>
				<div class="form-group">
					<%= t.text_area :content, class: "form-control", required: true %>
				</div>
					<%= t.submit class: "btn btn-default" %>
				<% end %>
		</div>
	</div>

app/views/comments/create.js.erb
// $('.new_comment').remove();
$("#comment_content").val(" ")
$('#added_comments').append('<div class="comment"><%= j @comment.content %></div>')
// $('#added_comments').append('<%= j nested_comments (@change.comments).arrange(:order => :created_at)  %>');

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'comment/form' %>

app/views/comments/new.js.erb
$("#new_link<%= j @comment.ancestry %>").hide().after("<%= j render "comments/form" %>")