config/routes.rb
Opinion::Application.routes.draw do
  resources :search_suggestions

  root 'welcome#index'
  resources :welcome
  resources :users
  resources :sessions
  resources :votes

  resources :changes do
    resources :comments
    member { post :vote }
  end
  resources :categories

  resources :states 

  post '/create' => 'vote#create' 

     get '/about', controller: 'welcome', action: 'about'

  

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
	belongs_to :category
	belongs_to :change
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations
	has_many :changes, through: :categorizations

end

app/models/change.rb
class Change < ActiveRecord::Base


	belongs_to :user
  belongs_to :state
	has_many :votes, :dependent => :destroy

  has_many :categorizations, :dependent => :destroy
  has_many :categories, through: :categorizations

  has_many :comments

  accepts_nested_attributes_for :categories
  accepts_nested_attributes_for :comments
  
	mount_uploader :picture, PictureUploader

  # validates_inclusion_of :format, in: %w( jpg gif png ), message: "extension %{value} is not included in the list"
  # validates_length_of :username, minimum: 3, too_short: 'please enter at least 3 characters'

	def trending_algorithm(gravity = 1.8)
		# For a given change
    # Find all votes
    # Points is the difference of upvotes and downvotes
    # Time is the difference between now and when the change was created (in hours)
    # gravity is fixed, but can override if necessary  
    points = self.aggregate
    time = ((Time.now - self.created_at) / 5760).round
    rank = (points - 1).to_f / ((time + 2)**gravity)
	end


  def aggregate
    self.up_votes - self.down_votes
  end


  def up_votes
     votes.select{|vote| vote.value == 1 }.size
  end

  def down_votes
    votes.select{|vote| vote.value == -1 }.size
  end


  def total_votes
     self.up_votes - self.down_votes
  end

  def total_voted
     self.up_votes + self.down_votes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_ancestry
	belongs_to :change
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :senator
	belongs_to :house
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :state

  def self.dedupe
  	groupded = all.group_by {|model| [model.first_name, model.last_name] }
    groupded.values.each do |dupes|
  	first_one = dupes.shift
  	dupes.each {|double| double.destroy}
	  end

  end


	
end

app/models/office_term.rb
class OfficeTerm < ActiveRecord::Base
	belongs_to :house
	belongs_to :senate
end

app/models/party.rb
class Party < ActiveRecord::Base
	has_many :senates
end

app/models/search_suggestion.rb
class SearchSuggestion < ActiveRecord::Base

	def self.terms_for(prefix)
    suggestions = where("term like ?", "#{prefix}_%")
    suggestions.order(:popularity).limit(10).pluck(:term)
	end

  def self.index_states
    State.find_each do |state|
      index_term(state.name)
      state.name.split.each { |t| index_term(t) }
    end
  end
  
  def self.index_term(term)
    where(term: term.downcase).first_or_initialize.tap do |suggestion|
      suggestion.increment! :popularity
    end
  end
end

app/models/senate.rb
class Senate < ActiveRecord::Base
	belongs_to :state
	has_one :contact
	belongs_to :party



  def self.dedupe
  	groupded = all.group_by {|model| [model.first_name, model.last_name] }
    groupded.values.each do |dupes|
  	first_one = dupes.shift
  	dupes.each {|double| double.destroy}
	  end
  end

end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :houses
	has_many :senates
	has_many :changes
	has_many :users
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :changes
	has_many :votes #, through: :changes
  belongs_to :state
	validates :username, presence: true
	validates :username, uniqueness: true
  validates :state_id, presence: true
	validates_confirmation_of :password

  # accepts_nested_attributes_for :state, reject_if: :new_record?
	has_secure_password





  def vote_for(change_id, value)
  	@vote = self.votes.where(change_id: change_id).first || self.votes.build(change_id: change_id)

	  if @vote.value.to_s == value
      @k = 0
    else
      @vote.value = value
      @vote.save!
      @k = value.to_i
    end 
    @k
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base

	belongs_to :change
	belongs_to :user

	# validates_uniqueness_of :change_id, scope: :user_id
	validates_inclusion_of :value, in: [1, -1]

#delete this?
	def self.aggregate_votes(change_id)
   self.where(upvote: true, change_id: change_id).count - self.where(upvote: false, change_id: change_id).count
	end

end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController

  def new
    @change = Change.new
    @change.categorizations.build
    @categories = Category.all
  end

  def create
		@change = Change.create(change_params)
    params["change"]["category_id"].each do |num|
      n = Category.find_by_name(num)
      c = Categorization.create(change_id: @change.id, category_id: n.id)
    end
		@change.user_id = session[:user_id]
    
   respond_to do |format|
  		if @change.save!
        format.html { redirect_to change_path(@change.id), notice: 'Created An Opinion' }
      end
    end
  end


  def show
    @change = Change.joins(:categories).find(params[:id])
  end


  def vote
    @k = current_user.vote_for(params[:id], params[:value]) if current_user
    respond_to do |format|
        format.js
    end
  end


private
  def change_params
    params.require(:change).permit! #(:name, :description, :picture, :user_id, :state_id, :category_id)
  end

  def find_state
     State.where(name: params[:search].capitalize).pop.id
  end

    def vote_params
    params.require(:vote).permit!
  end


end

app/controllers/states_controller.rb
class StatesController < ApplicationController

	def show
		@state = State.find_by_name(params[:search].capitalize)
	end

private

  def state_params
  	params.require(:state).permit(:name)
  end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		state = State.find_by_name(params[:search].capitalize)
		@user.state_id = state.id if state

		respond_to do |format|
			if @user.save
				login(@user)
				format.html { redirect_to(:root, notice: 'User was successfully created.') }
			else 
				 format.html { render action: "new"}
				 format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end

	end

	 private

  def user_params
    params.require(:user).permit(:username, :password_digest, :password, :password_confirmation, :id, :state_id)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  def create
    session[:change_ids] ||= []
    if session[:change_ids].include?(params[:vote][:change_id]) && session[:change_ids].length < 10
       flash.now[:notice] = "You already voted"
    else
      session[:change_ids] << params[:vote][:change_id]
    	@vote = Vote.create(vote_params)
      @vote.save!
      @aggregate_votes = Vote.aggregate_votes(params[:vote][:change_id])
      @change_id = params[:vote][:change_id]
    end

	  	respond_to do |format|
        if @vote
  	      format.js 
          format.html { redirect_to(change_path(params[:vote][:change_id])) }
        else
          redirect_to :back, alert: "Unable to vote, perhaps you already did."
        end
  		end

  end


private

  def vote_params
  	params.require(:vote).permit(:upvote, :change_id, :user_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


	def index
		@changes = Change.all
		@changes = @changes.sort_by { |c| c.trending_algorithm }.last(9).reverse
		@categories = Category.all
	end

	def about
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(page_title)
		content_for(:title) { page_title  }
	end
end

app/helpers/changes_helper.rb
module ChangesHelper

 def twitter_handles(senates, sep = ", @")
 	 senates.map {|senate| senate.contact.twiter }.join sep
 end
end

app/helpers/comments_helper.rb
module CommentsHelper

	def nested_comments(comments)
	 comments.map do |comment, sub_comments|
	    render(comment) + content_tag(:div)
	  end.join.html_safe
	end
end

app/helpers/votes_helper.rb
module VotesHelper

	#if current_user has voted on this issue
  def vote_users
  	if current_user
  		return "yes_vote"
  	else
  		return "not_vote"
  	end
  end
end

app/views/states/index.html.erb
<% @states.each do |state| %>
<%= state %>
<% end %>

app/views/states/show.html.erb
<div class="row">
	<div id="senator-changes" class="col-sm-9">
		<h1 class="text-center">Vipers in <%= @state.name %></h1>
		<br />
			<% @state.changes.each do |change| %>
				<div class="col-md-4 intro-box text-center" id="<%= change.id %>">
					<p ><%= link_to "#{change.name.upcase}", change_path(change.id) %></p>
					<p> <%= link_to "Created By: #{change.user.username}", user_path(change.user_id) if change.user %>
					<p><%= image_tag change.picture_url(:thumb) %></p>
					<p class="voted"><%= link_to 'up', votes_path(vote: {upvote: true, change_id: change.id} ), :method => :post, remote: true  %> |
					<%= link_to 'down', votes_path(vote: { upvote: false, change_id: change.id }), :method => :post, remote: true %></p>

					<p class="votes">Total Votes: <%= change.aggregate %></p>
				</div>
			<% end %>
	</div>
	<div id="sidebar" class="col-sm-3">
	<h3><%= @state.abbreviation %> Representatives</h3>
	<h4>Senators</h4>
		<% @state.senates.each do |member| %>
			<p><%= member.first_name %>
				<%= member.last_name %>
				Party: <%= member.party %>
				Twiter : <%= link_to "Twiiter", "https://twitter.com/#{member.twiter}" %>
				facebook: <%= link_to "facebook", "https://www.facebook.com/#{member.facebook}" %>
				phone: <%= member.phone %>
			</p>
		<% end %>


	<h4>House Members</h4>
	<% @state.houses.each do |member| %>
		<p><%= member.first_name %>
		<%= member.last_name %>
		Party: <%= member.party %>
		Twiter : <%= link_to "Twiiter", "https://twitter.com/#{member.twiter}" %>
		facebook: <%= link_to "facebook", "https://www.facebook.com/#{member.facebook}" %>
		phone: <%= member.phone %>
	<% end %>

	</div> 
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-5 col-md-offset-3">
		<%= form_for @user, :html => {:role => "form"} do |t| %>
		 <%= render "shared/error_messages", :target => @user %>
		   <div class="form-group">
				<%= t.label :username %>
				<%= t.text_field :username, class: "form-control", required: true, autofocus: true %>
			</div>
			<div class="form-group">
			<%= t.label :state %> : <a data-toggle="tooltip" data-placement="top" title="Provides Contacts for Congress">why?</a> 
			 <%= text_field_tag :search, params[:search], size: 30, class: "form-control", required: true, placeholder: "Search By State" %>
			</div>
			<div class="form-group">
			<%= t.label :password %>
			 <%= t.password_field :password, class: "form-control", required: true %>
			</div>
			<div class="form-group">
			 <%= t.label :confirm_password %>
			 <%= t.password_field :password_confirmation, class: "form-control", required: true %>
			</div>
			<br />
			<%= t.submit class: "btn btn-default" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h2>Welcome <%= @user.username %></h2>

<div class="row">

	<% @user.changes.each do |change| %>
	<div class="col-md-2 intro-box text-center">
		<p><%=link_to change.name, change_path(change.id) %></p>
		<p><%= image_tag change.picture_url(:thumb) %></p>
		<p><%= change.description %></p>
	</div>
	<% end %>
</div>

<div class="row text-center">
<% @user.state.senates.each do |senator| %>
<div class="col-md-4">
	<p>Name: <%= senator.first_name %> <%= senator.last_name %></p>
	<p>Party: <%= senator.party.name %></p>
	<p>Twitter: <%= link_to "@#{senator.contact.twiter}", "https://www.facebook.com/#{senator.contact.twiter}" %></p>
	<p>Facebook: <%= link_to "Facebook", "https://www.facebook.com/#{senator.contact.facebook}" %></p>
</div>
<% end %>

</div>
<!-- t.string :first_name, :last_name, :middle_name, :party, :twiter, :facebook, :contact, :phone, :youtub_id, :website, :gender, :term_start, :term_end -->