config/routes.rb
Opinion::Application.routes.draw do
  resources :search_suggestions

  root 'welcome#index'
  resources :welcome
  resources :users
  resources :sessions
  resources :votes

  resources :changes do
    resources :comments
    member { post :vote }
  end
  resources :categories

  resources :states 

  post '/create' => 'vote#create' 

     get '/about', controller: 'welcome', action: 'about'

  

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
	belongs_to :category
	belongs_to :change
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations
	has_many :changes, through: :categorizations

end

app/models/change.rb
class Change < ActiveRecord::Base


	belongs_to :user
  belongs_to :state
	has_many :votes, :dependent => :destroy

  has_many :categorizations, :dependent => :destroy
  has_many :categories, through: :categorizations

  has_many :comments

  accepts_nested_attributes_for :categories
  accepts_nested_attributes_for :comments
  
	mount_uploader :picture, PictureUploader

  # validates_inclusion_of :format, in: %w( jpg gif png ), message: "extension %{value} is not included in the list"
  # validates_length_of :username, minimum: 3, too_short: 'please enter at least 3 characters'

	def trending_algorithm(gravity = 1.8)
		# For a given change
    # Find all votes
    # Points is the difference of upvotes and downvotes
    # Time is the difference between now and when the change was created (in hours)
    # gravity is fixed, but can override if necessary  
    points = self.aggregate
    time = ((Time.now - self.created_at) / 5760).round
    rank = (points - 1).to_f / ((time + 2)**gravity)
	end


  def aggregate
    self.up_votes - self.down_votes
  end


  def up_votes
     votes.select{|vote| vote.value == 1 }.size
  end

  def down_votes
    votes.select{|vote| vote.value == -1 }.size
  end


  def total_votes
     self.up_votes - self.down_votes
  end

  def total_voted
     self.up_votes + self.down_votes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_ancestry
	belongs_to :change
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :senator
	belongs_to :house
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :state

  def self.dedupe
  	groupded = all.group_by {|model| [model.first_name, model.last_name] }
    groupded.values.each do |dupes|
  	first_one = dupes.shift
  	dupes.each {|double| double.destroy}
	  end

  end


	
end

app/models/office_term.rb
class OfficeTerm < ActiveRecord::Base
	belongs_to :house
	belongs_to :senate
end

app/models/party.rb
class Party < ActiveRecord::Base
	has_many :senates
end

app/models/search_suggestion.rb
class SearchSuggestion < ActiveRecord::Base

	def self.terms_for(prefix)
    suggestions = where("term like ?", "#{prefix}_%")
    suggestions.order(:popularity).limit(10).pluck(:term)
	end

  def self.index_states
    State.find_each do |state|
      index_term(state.name)
      state.name.split.each { |t| index_term(t) }
    end
  end
  
  def self.index_term(term)
    where(term: term.downcase).first_or_initialize.tap do |suggestion|
      suggestion.increment! :popularity
    end
  end
end

app/models/senate.rb
class Senate < ActiveRecord::Base
	belongs_to :state
	has_one :contact
	belongs_to :party



  def self.dedupe
  	groupded = all.group_by {|model| [model.first_name, model.last_name] }
    groupded.values.each do |dupes|
  	first_one = dupes.shift
  	dupes.each {|double| double.destroy}
	  end
  end

end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :houses
	has_many :senates
	has_many :changes
	has_many :users
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :changes
	has_many :votes #, through: :changes
  belongs_to :state
	validates :username, presence: true
	validates :username, uniqueness: true
  validates :state_id, presence: true
	validates_confirmation_of :password

  # accepts_nested_attributes_for :state, reject_if: :new_record?
	has_secure_password





  def vote_for(change_id, value)
  	@vote = self.votes.where(change_id: change_id).first || self.votes.build(change_id: change_id)

	  if @vote.value.to_s == value
      @k = 0
    else
      @vote.value = value
      @vote.save!
      @k = value.to_i
    end 
    @k
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base

	belongs_to :change
	belongs_to :user

	# validates_uniqueness_of :change_id, scope: :user_id
	validates_inclusion_of :value, in: [1, -1]

#delete this?
	def self.aggregate_votes(change_id)
   self.where(upvote: true, change_id: change_id).count - self.where(upvote: false, change_id: change_id).count
	end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController

	def show
		@state = State.find_by_name(params[:search].capitalize)
	end

private

  def state_params
  	params.require(:state).permit(:name)
  end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		state = State.find_by_name(params[:search].capitalize)
		@user.state_id = state.id if state

		respond_to do |format|
			if @user.save
				login(@user)
				format.html { redirect_to(:root, notice: 'User was successfully created.') }
			else 
				 format.html { render action: "new"}
				 format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end

	end

	 private

  def user_params
    params.require(:user).permit(:username, :password_digest, :password, :password_confirmation, :id, :state_id)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  def create
    session[:change_ids] ||= []
    if session[:change_ids].include?(params[:vote][:change_id]) && session[:change_ids].length < 10
       flash.now[:notice] = "You already voted"
    else
      session[:change_ids] << params[:vote][:change_id]
    	@vote = Vote.create(vote_params)
      @vote.save!
      @aggregate_votes = Vote.aggregate_votes(params[:vote][:change_id])
      @change_id = params[:vote][:change_id]
    end

	  	respond_to do |format|
        if @vote
  	      format.js 
          format.html { redirect_to(change_path(params[:vote][:change_id])) }
        else
          redirect_to :back, alert: "Unable to vote, perhaps you already did."
        end
  		end

  end


private

  def vote_params
  	params.require(:vote).permit(:upvote, :change_id, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(page_title)
		content_for(:title) { page_title  }
	end
end

app/helpers/changes_helper.rb
module ChangesHelper

 def twitter_handles(senates, sep = ", @")
 	 senates.map {|senate| senate.contact.twiter }.join sep
 end
end

app/helpers/comments_helper.rb
module CommentsHelper

	def nested_comments(comments)
	 comments.map do |comment, sub_comments|
	    render(comment) + content_tag(:div)
	  end.join.html_safe
	end
end

app/helpers/votes_helper.rb
module VotesHelper

	#if current_user has voted on this issue
  def vote_users
  	if current_user
  		return "yes_vote"
  	else
  		return "not_vote"
  	end
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="row span-12">
		<div class="footer navbar-fixed-bottom">
			<div class="muted text-center">Opinionator &copy; 2014</div>
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top" role="navigation">
	<%= link_to image_tag("logo-change.png"), root_path, class: "navbar-brand img-responsive" %>
	<ul class="nav navbar-nav pull-right">
	  <li><%= link_to 'Create Opinion', new_change_path %></li>
		<% if current_user %>
	     <li><%= link_to "Profile", user_path(current_user) %></li>
		  <li><%= link_to 'Logout', session_path(current_user), :method => :delete %></h2>
		  </li>
		  <% else %>
		<li><%= link_to "create account", new_user_path %></li>
		<li><%= link_to "login", new_session_path %></li>
		<% end %>
		 <li><%= link_to 'About', about_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : "Opinionator - My Opinions Matter " %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'star.ico' %>
</head>
<body>
	<%= render "layouts/navigation" %>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

	<div class="container">
		<%= yield %>
	</div>
 

   
<footer>
 <%= render "layouts/footer" %>
</footer>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <p><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</p>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>